export const cities = [
    "Tuguegarao",
    "Ilagan",
    "Cauayan",
    "Santiago",
    "Baguio",
    "San Fernando",
    "Dagupan",
    "Urdaneta",
    "Tarlac",
    "Angeles",
    "Caloocan",
    null,
    "Quezon",
    "Marikina",
    "Antipolo",
    "Olongapo",
    "Bulacan",
    null,
    "Manila",
    "Makati",
    "Pasig",
    "Pasay",
    "Taguig",
    "Parañaque",
    "Muntinlupa",
    "Cavite City",
    "Imus",
    "Dasmariñas",
    "Bacoor",
    "Batangas City",
    "Lipa",
    "Tanauan",
    "Lucena",
    "Tayabas",
    null,
    null,
    null,
    "San Jose del Monte",
    "Malolos",
    "Meycauayan",
    "Balanga",
    "Subic",
    null,
    null,
    "Alaminos (Pangasinan)",
    "San Carlos (Pangasinan)",
    "Laoag (Ilocos Norte)",
    "Vigan (Ilocos Sur)",
    "Aparri (Cagayan)",
    "Bayombong (Nueva Vizcaya)",
];
